INSERT INTO interests (name) VALUES ('Arts')
INSERT INTO interests (name) VALUES ('Culture')
INSERT INTO interests (name) VALUES ('Food')
INSERT INTO interests (name) VALUES ('Hiking')
INSERT INTO interests (name) VALUES ('Landmarks')
INSERT INTO interests (name) VALUES ('Music')
INSERT INTO interests (name) VALUES ('Shopping')
INSERT INTO interests (name) VALUES ('Sports')
